
export default [
  {
    category: "Western",
    title: "Hero",
    // image: icons.hero,
    // icon: <GiSpinningSword size="1.3rem" />,
    instructions: "The name should be someone who sounds heroic.",
    data: [
      "**Thalia** the Thundermaiden",
      "**Aragorn** the Rightful King of Gondor",
      "**Mirabel** Starshield",
      "**Thaedon** Guardian of the Ancients",
      "**Caladan** Lord of the Cosmic Realm",
      "**Kvothe** the Arcane Prodigy",
      "Archangel **Avacyn**",
      "**Valdrim** the Stormbringer",
      "**Elysia** the Valiant",
      "**Vaelin** the Braveheart of the Lost Realm",
      "**Elysar** the Windwalker",
      "**Tiriala** Moonbeam",
      "Admiral **Beckett Brass**",
      "**Alesha** Who Smiles at Death",
      "**Lyria** Silvervoice",
      "**Isolde** the Stormbringer",
      "**Revan** Lord of the Thume",
      "**Torrin** of the Broken Blade",
    ],
  },
  {
    category: "Western",
    title: "Benevolent",
    // image: icons.benevolent,
    // icon: <FaLeaf size="1.3rem" />,
    instructions:
      "The name should be someone who is kind and loving. A friend.",
    data: [
      "**Arwen** Mortal Queen",
      "**Butterbur** Bree Innkeeper",
      "**Emmara** Soul of the Accord",
      "**Frodo Baggins**",
      "**Melira** the Living Cure",
      "**Samwise Gamgee**",
      "**Selvala** Explorer Returned",
      "**Astrid Peth**",
      "**Bennie Bracks** Zoologist",
      "**Gandalf** the White",
    ],
  },
  {
    category: "Western",
    title: "Dark Lord",
    // image: icons.darkLord,
    // icon: <GiEvilBat size="1.3rem" />,
    instructions: "The name should be something who sounds diabolical.",
    data: [
      "**Ebondeath** Dracolich",
      "**Brisela** Voice of Nightmares",
      "**Ashcoat** of the Shadow Swarm",
      "**Asmodeus** the Archfiend",
      "Demonlord **Belzenlok**",
      "**Erebos** God of the Dead",
      "**Gollum** Obsessed Stalker",
      "**Go-Shintai** of Hidden Cruelty",
      "**Griselbrand** He Who Hungers",
      "**Kaervek** the Spiteful",
      "**Kalitas** Traitor of Ghet",
      "**Korlash** Heir to Blackblade",
      "**K'rrik** Son of Yawgmoth",
      "**Mikaeus** the Unhallowed",
      "**Nefarox** Overlord of Grixis",
      "**Ob Nixilis** the Fallen",
      "**Razaketh** the Foulblooded",
      "**Seizan** Perverter of Truth",
      "**Sheoldred** Whispering One",
      "**Skithiryx** the Blight Dragon",
      "**Yawgmoth** Thran Physician",
    ],
  },
  {
    category: "Western",
    title: "Wizard",
    // image: icons.wizard,
    // icon: <FaHatWizard size="1.3rem" />,
    instructions:
      "The name should be for a wizard. Wise, ancient, and magical.",
    data: [
      "**Arcanis** the Omnipotent",
      "**Arjun** the Shifting Flame",
      "**Azami** Lady of Scrolls",
      "**Barrin** Tolarian Archmage",
      "**Gadwick** the Wizened",
      "**Gandalf** of the Secret Fire",
      "**Gorion** Wise Mentor",
      "**Jace** Vryn's Prodigy",
      "**Naban** Dean of Iteration",
      "**Naru Meha** Master Wizard",
      "**Niv-Mizzet** the Firemind",
      "**Orion** the Mystic Scholar",
      "**Rayne** Academy Chancellor",
      "**Riku** of Two Reflections",
      "**Saruman** of Many Colors",
      "**Teferi** Mage of Zhalfir",
      "**Albus Dumbledore** Headmaster of Magic",
    ],
  },
  {
    category: "Western",
    title: "Grembo",
    // image: icons.grembo,
    // icon: <GiEvilMinion size="1.3rem" />,
    instructions:
      "The name should be of a small, dirty, sneaky, goofy creature.",
    data: [
      "**Squidgle** Leaky-Toes",
      "**Fremkin** Eater of the Last Piece of Pie",
      "**Skipit** Fish Oil Salesman",
      "**Dobby** the Free Elf",
      "**Grimble** the Puddle Finder",
      "**Smudge** the Dung Seeker",
      "**Kib** the Stench Breather",
    ],
  },
  {
    category: "Western",
    title: "Construct",
    // image: icons.construct,
    // icon: <GiRockGolem size="1.3rem" />,
    instructions: "The name should be for an ancient construct.",
    data: [
      "**Nosiron** the Sundering Colossus",
      "**Acronis** the Time-Ward Sentinel",
      "**Bosh** Iron Golem",
      "**Golos** Tireless Pilgrim",
      "**Liberator** Urza's Battlethopter",
      "The **Peregrine Dynamo**",
      "**Karn** Silver Golem",
    ],
  },
  {
    category: "Ancestry",
    title: "Dwarf",
    // image: icons.dwarf,
    // icon: <GiDwarfFace size="1.3rem" />,
    instructions:
      "These should be dwarf names. Dwarves honor their children with names taken from ancestors or dwarven heroes, and it’s quite rare to invent a new name or to borrow a name from another culture for a child. When introducing themselves, dwarves tend to list their family and clan, plus any number of other familial connections and honorifics. Dwarven names usually contain hard consonants and are rarely more or fewer than two syllables.",
    data: [
      "**Agna** the Forge Mistress",
      "**Bodill** Warden of the Deeps",
      "**Dolgrin** Champion of the Stoneskin Clans",
      "**Edrukk** the Iron fist",
      "**Grunyar** the Stoneheart Herald",
      "**Ingra** the Everflame",
      "**Kazmuk** the Runesmith",
      "**Kotri** the Smoky-Eyed",
      "**Lupp** Bringer of Silences",
      "**Morgrym** Hammer of the Depths",
      "**Rogar** the Alestorm Maker",
      "**Rusilka** Healer of the Iron Vein",
      "**Torra** the Gem Whisperer",
      "**Yangrit** the Ruby-Eyed Shieldbearer",
    ],
  },
  {
    category: "Ancestry",
    title: "Elf",
    // image: icons.elf,
    // icon: <GiElfEar size="1.3rem" />,
    instructions:
      "These should be elf names. An elf keeps their personal name secret among their family, while giving a nickname when meeting other people. This nickname can change over time, due to events in the elf’s life or even on a whim. A single elf might be known by many names by associates of different ages and regions. Elven names consist of multiple syllables and are meant to flow lyrically—at least in the Elven tongue. They so commonly end in “-el” or “-ara” that other cultures sometimes avoid names ending in these syllables to avoid sounding too elven.",
    data: [
      "**Aerel** the Whispering Wind",
      "**Amrunelara** Princess of Moonlight",
      "**Caladrel** Keeper of the Forest Depths",
      "**Dardlara** the Star Voyager",
      "**Faunra** the Enchantress of Emerald Glades",
      "**Heldalel** the Archer of Ethereal Darkness",
      "**Jathal** the Crimson Blade",
      "**Lanliss** the Silent Shadow",
      "**Oparal** the Guardian of Ancient Lore",
      "**Seldlon** the Flame Warden",
      "**Soumral** the Sage of Sunlit Seas",
      "**Talathel** the Sentinel of Sorrowful Skies",
      "**Tessara** the Dreamweaver",
      "**Variel** the Songbird of Venus Dusk",
      "**Yalandlara** the Maiden of Mystic Meadows",
      "**Zordlon** the Storm Bringer",
    ],
  },
  {
    category: "Ancestry",
    title: "Gnome",
    // image: icons.gnome,
    // icon: <GiBadGnome size="1.3rem" />,
    instructions:
      "These should be gnome names. Gnome names can get quite complex and polysyllabic. They have little interest in familial names, and most children receive their names purely on a parent’s whim. Gnomes rarely concern themselves with how easy their names are to pronounce, and they often go by shorter nicknames. Some even collect and chronicle these nicknames. Among gnomes, the shorter the name, the more feminine it’s considered to be.",
    data: [
      "**Abroshtor** the Enchanted Tinkerer",
      "**Bastargre** the Stonehearted",
      "**Besh** the Fabled Mechanist",
      "**Fijit** the Dreamweaver",
      "**Halungalom** the Star Navigator",
      "**Krolmnite** the Ore Whisperer",
      "**Neji** the Illusionist Alchemist",
      "**Majet** the Clockwork Genius",
      "**Pai** the Sapphire Artisan",
      "**Poshment** the Spellbound Botanist",
      "**Queck** the Mystic Forger",
      "**Trig** the Tempest Tamer",
      "**Zarzuket** the Rune Guardian",
      "**Zatqualmie** the Silvertongue Enigma",
    ],
  },
  {
    category: "Ancestry",
    title: "Goblin",
    // image: icons.goblin,
    // icon: <GiGoblinHead size="1.3rem" />,
    instructions:
      "These should be goblin names. Goblins keep their names simple. A good name should be easy to pronounce, short enough to shout without getting winded, and taste good to say. The namer often picks a word that rhymes with something they like so that writing songs is easier. Since there aren’t any real traditions regarding naming in goblin culture, children often name themselves once they’re old enough to do something resembling talking.",
    data: [
      "**Ak** the Sly Trickster",
      "**Bokker** Flame-Keeper of the Depths",
      "**Frum** Ravager Below the Mountains",
      "**Guzmuk** the Shadow Skulker",
      "**Krobby** Guardian of the Jade Crypt",
      "**Loohi** Whisperer in the Caverns",
      "**Mazmord** the Crimson Warrior",
      "**Neeka** the Chieftain's Cunning Daughter",
      "**Omgot** Bane of the Bright Daylight",
      "**Ranzak** the Ruthless Marauder",
      "**Rickle** the Mischievous Gadgeteer",
      "**Tup** the Underbridge Menace",
      "**Wakla** the Crafty Trap Smith",
      "**Yonk** the Fierce-Eyed Warcrier",
      "**Zibini** Sorcerer of the Potion Cauldron",
    ],
  },
  {
    category: "Ancestry",
    title: "Halfling",
    // image: icons.halfling,
    // icon: <GiClover size="1.3rem" />,
    instructions:
      "These should be halfling or hobbit names. Halfling names are usually two to three syllables, with a gentle sound that avoids hard consonants. Preferring their names to sound humble, halflings see overly long or complex names as a sign of arrogance. This goes only for their own people, however—halflings have names that suit them, and they understand that elves and humans might have longer names to suit their own aesthetics. Humans in particular have a tendency to refer to halflings by nicknames, with “Lucky” being common to the point of absurdity.",
    data: [
      "**Anafa** the Sprightly Wanderer",
      "**Antal** Keeper of Treasures",
      "**Bellis** the Evercheerful",
      "**Boram** the Stout-hearted Brewer",
      "**Etune** Whisperer of the Wind",
      "**Filiu** the Leaf Dancer",
      "**Jamir** Guardian of the Harvest",
      "**Kaleb** the Gentle Storyteller",
      "**Linna** the Night Singer",
      "**Marra** the Hearth Keeper",
      "**Miro** the Pipe-weed Farmer",
      "**Rillka** Warden of the Riverbanks",
      "**Sistra** the Jovial Baker",
      "**Sumak** the Star Reader",
      "**Yamyra** the Berry Gatherer",
    ],
  },
  {
    category: "Ancestry",
    title: "Azarketi",
    // image: icons.azarketi,
    // icon: <GiMermaid size="1.3rem" />,
    instructions:
      "These should be azarketi names. Azarketis often take the names of nautical, weather, or geographical features important to the azarketi's family. Other azarketi groups will choose human names in order to encourage conformity with surface cultures. Some azarketi names have been passed down through so many generations that they still use ancient Azlanti roots or refer to bodies of water that no longer exist.",
    data: [
      "**Aft** the Undaunted Voyager",
      "**Aliz** Mistress of the Aquatic Realm",
      "**Cascade** the Tidal Sorceress",
      "**Delta** the Stormbringer",
      "**Harbor** Guardian of Safe Shores",
      "**Ilani** the Seaborn Enchantress",
      "**Inkua** the Ebb-Flow Seer",
      "**Jib** the Sagasail",
      "**Lagoon** the Ethereal Mariner",
      "**Lobay** the Kraken Whisperer",
      "**Marine** the Serpentbane",
      "**Tidal** the Wave Warden",
      "**Windward** the Gale Dancer",
      "**Zarket** the Trident King",
    ],
  },
  {
    category: "Ancestry",
    title: "Catfolk",
    // image: icons.catfolk,
    // icon: <GiCat size="1.3rem" />,
    instructions:
      "These should be catfolk names. Catfolk are given short names in their youth. Adolescent catfolk are free to choose a different name when they first leave home, though some simply keep the name they’ve gotten used to. Catfolk love to add titles and honorifics to their names. Some catfolk use their titles exclusively among non-catfolk, and so become known by epithets like Six Fates, Fiend Killer, or Mistcloak.",
    data: [
      "**Alyara** Dreamweaver",
      "**Crinto** the Claw-sworn",
      "**Drewan** Starwhisker",
      "**Espes** the Whispering Predator",
      "**Ferrus** Thunderpurr",
      "**Gerran** Keeper of the Veiled Secrets",
      "**Halhat** Flamefoot",
      "**Hoya** the Starlit Huntress",
      "**Ruun** the Lightning-eyed Warrior",
      "**Sevastin** the Silent Roar",
      "**Tespa** the Moonshadow Dancer",
      "**Aenaris** Whisperwind",
      "**Yonsol** the Light-footed Wanderer",
      "**Zakkar** the Fireheart Voyager",
      "**Zathra** the Spirit-tailed Mystic",
      "**Baishan** Stormpelt",
    ],
  },
  {
    category: "Ancestry",
    title: "Fetchling",
    // image: icons.fetchling,
    // icon: <GiCloak size="1.3rem" />,
    instructions:
      "These should be fetchling names. Fetchlings adapted to a new world, and their names do the same. These names commonly include phonetic qualities from multiple languages or are simply local cultural names that fetchling families find compelling. Other dominant naming conventions include flowing sounds, harsh or hissing consonants, and surnames that refer to important relatives or community traits.",
    data: [
      "**Amelisce** the Shadow Weaver",
      "**Ashka** of the Ethereal Voids",
      "**Drosil** the Nightbreath",
      "**Eitsanara** the Twilight Whisperer",
      "**Eomva** the Illusionary Trickster",
      "**Ikyamek** the Stargazer of Shadows",
      "**Inva** the Eclipsed Enigma",
      "**Jegan** the Gloomblade",
      "**Lirtae** the Sable Seer",
      "**Meotrai** the Obsidian Sorcerer",
      "**Sorsul** the Veiled Vagabond",
      "**Zokaratz** the Dusk Dweller",
    ],
  },
  {
    category: "Ancestry",
    title: "Gnoll",
    // image: icons.gnoll,
    // icon: <GiHyenaHead size="1.3rem" />,
    instructions:
      "These should be gnoll names. Newborn kholo are given a root name, typically that of a bone, plant, or animal (though never Hyena, as this is considered narcissistic and arrogant). As a gnoll reaches certain milestones in life, they add descriptors to their name. Root names are often passed down through families, while descriptors are chosen to fit the gnoll's personality, usually in raucous ceremonies.",
    data: [
      "**Baobab** Rooted in Magic",
      "**Jackal** the Cunning Trickster",
      "**Onyx Elephant** in Shadows",
      "**Red Thorn** Heart of the Crimson Rose",
      "**Unbent Iron Reed** Stand of the Steadfast Soldier",
      "**White Acacia** Blossom in the Moonlight",
      "**Wistful Tooth** Bidden Memories of the Wild",
      "**Woodpecker** Feathered Drumbeat of the Forest",
    ],
  },
  {
    category: "Ancestry",
    title: "Grippli",
    // image: icons.grippli,
    // icon: <GiFrog size="1.3rem" />,
    instructions:
      "These should be grippli names. Grippli names often include resonant vowels and chirped consonants that remain difficult for non-gripplis to vocalize properly. Gripplis that travel widely often adopt one or more names more easily replicated by their associates.",
    data: [
      "**Aalpo'ol** the Enchanted Seer",
      "**Bogwynne** Mistress of the Silent Swamps",
      "**Ctaprak** Holder of the Moonstone Sceptre",
      "**Eegru** the Mystic Raincaller",
      "**Gpoun** the Watercolor Whisperer",
      "**Gruoksh** the Keeper of Emerald Shadows",
      "**Hrrauti** Dancer in the Twilight Mists",
      "**Iopo** the Dawn's Serenade",
      "**Iykiki** Trill of the Golden Frogs",
      "**Kyrsiik** the Firefly Weaver",
      "**Mhruugu** the Hymn of Midnight Marsh",
      "**Oplugo** the Orchid's Guardian",
      "**Quaasol** the Sunstone's Secret",
      "**Yolkuu** the Jade Circlet's Verity",
      "**Ztaal** the Guardian of the Sapphire Springs",
    ],
  },
  {
    category: "Ancestry",
    title: "Hobgoblin",
    // image: icons.hobgoblin,
    // icon: <GiMightyForce size="1.3rem" />,
    instructions:
      "These should be hobgoblin names. Like goblins, hobgoblin names tend to be simple, though hobgoblin names usually sound more guttural and forceful. On rare occasions, hobgoblins will alter their names, keeping the core but adding aspects, usually in response to an extreme trauma or a life-altering event. Hobgoblins have no surnames, considering them both pointless and presumptuous; an individual’s merits and demerits are to be earned by their actions, not by an association with a particular lineage.",
    data: [
      "**Aze** the Dreamweaver",
      "**Druknar** Guardian of the Shadow Falls",
      "**Ghargam** Sovereign of Emerald Glen",
      "**Hathkren** the Spiritcaller",
      "**Imakra** the Mystic Flame",
      "**Kralaeng** Wielder of the Thunder Hammer",
      "**Mazkol** the Stone Hearted",
      "**Olzu** Keeper of Whispering Winds",
      "**Rezal** the Frostbound",
      "**Sivkrag** the Breaker of Chains",
      "**Volmak** the Iron Fist",
      "**Zornum** Master of the Midnight Sun",
    ],
  },
  {
    category: "Ancestry",
    title: "Kitsune",
    // image: icons.kitsune,
    // icon: <GiFox size="1.3rem" />,
    instructions:
      "These should be kitsune names. While kitsune have some traditional names, they're more likely to use names that are unremarkable in their local society, the better to pass unnoticed. Some have different names for each form: a kitsune name for their kitsune form, a regional name for a tailless form, and possibly no name at all for a fox form.",
    data: [
      "**Hamako** the Nine-Tailed Conqueror",
      "**Haohiko** the Flame-touched Whisperer",
      "**Kitsukou** Jewel of the Mystic Flame",
      "**Kon** the Shadow Embraced Enigma",
      "**Kwan-la** the Enchantress of Moonlight",
      "**Talaro** the Sage of the Crimson Forest",
    ],
  },
  {
    category: "Ancestry",
    title: "Leshy",
    // image: icons.leshy,
    // icon: <PiPlantFill size="1.3rem" />,
    instructions:
      "These should be leshy names. Leshies choose and change their names multiple times throughout their lives. These names often represent a facet of their personalities or values, though another common naming convention is to use descriptions of a natural feature they admire. Some leshies even use a cycle of names that changes to align with natural phenomena, such as names based upon the season or the time of day.",
    data: [
      "**Scarlet in Summer** the Blossoming Harbinger",
      "**Verdant Taleweaver** the Ancient Lorekeeper",
      "**Lurking Hunter** the Vigilant Predator",
      "**Masterful Sun Drinker** the Solar Enchanter",
      "**Noon Sky Evening Song** the Lifegiver",
      "**Snowy Pine Branch** the Kind",
      "**Cascading Rapids** the Torrential Voyager",
    ],
  },
  {
    category: "Ancestry",
    title: "Lizardfolk",
    // image: icons.lizardfolk,
    // icon: <GiLizardTongue size="1.3rem" />,
    instructions:
      "These should be lizardfolk names. Lizardfolk names come from their ancient language and tend to be traditional. Names are typically chosen by the clan’s astrologer in accordance to omens and which star signs are ascendant when an iruxi egg hatches, though occasionally an iruxi’s parents may name a hatchling for an ancestor or a beloved historical hero.",
    data: [
      "**Arasheg** the Twilight Astrologer",
      "**Barashk** the Jade Sentinel",
      "**Essaru** Sovereign of Emerald Marshes",
      "**Tizkar** the Skull Collector",
      "**Enshuk** Warden of the Winding Rivers",
      "**Gishkim** the Jade Claw Wielder",
      "**Hazi** the Silent Predator",
      "**Inishish** Guardian of Constellations",
      "**Kutak** the Crimson Crested",
      "**Nasha** the Sun-Stalker",
      "**Shulkuru** the Bonekeeper",
      "**Utakish** the Opalescent Oracle",
      "**Zelkekek** the Zephyr of the Ziggurat",
    ],
  },
  {
    category: "Ancestry",
    title: "Nagaji",
    // image: icons.nagaji,
    // icon: <GiSandSnake size="1.3rem" />,
    instructions:
      "These should be nagaji names. Nagaji names vary depending on what region of the world they occupy, but they tend to possess short vowels when they have any at all. Nagaji usually name themselves or allow groups of siblings to name each other as children, a tradition that often sees nagaji eagerly shedding these names for new ones when they reach adulthood.",
    data: [
      "**Adesha** of the Serpent Altar",
      "**Garija** Whisperer of the Emerald Scales",
      "**Kaya** Warden of the Obsidian Coils",
      "**Kuwana** the Sapphire Shieldbearer",
      "**Onok** Conquistador of the Azure Fang",
      "**Paravata** Champion of the Slithering Shadows",
      "**Sheni** Sentinel of the Opal Oasis",
      "**Takasha** Guardian of the Copper Carapace",
      "**Tasi** Herald of the Pythoonstaff",
      "**Ulu** Perceiver of the Hissing Heavens",
      "**Vaski** Emerald Enchanter",
      "**Yulbin** Bringer of the Whispering Whirlwind",
    ],
  },
  {
    category: "Ancestry",
    title: "Orc",
    // image: icons.orc,
    // icon: <GiOrcHead size="1.3rem" />,
    instructions:
      "These should be orc names. Orcs have a harsh, guttural language, and their naming conventions are no exception. Many orc names are simply the Orcish word for a particularly desirable trait, such as great strength, height, or ferocity. Orcs commonly use either their hold name or a name referencing a particularly memorable accomplishment as their surname.",
    data: [
      "**Arkus** the Ironbane",
      "**Ausk** the Fierce-Eyed",
      "**Durra** the Mountain's Roar",
      "**Grask** the Bloodied Fury",
      "**Grillgiss** Earthbreaker",
      "**Krugga** the Skullsplitter",
      "**Mahja** Wargrider",
      "**Murdut** the Ember's Rage",
      "**Ollak** the Thunderstrike",
      "**Onyat** Moon's Howler",
      "**Thurk** the Silent Blade",
      "**Uirch** the Demon Slayer",
      "**Unach** of the Black Blade",
    ],
  },
  {
    category: "Ancestry",
    title: "Kobold",
    // image: icons.kobold,
    // icon: <GiBoxTrap size="1.3rem" />,
    instructions:
      "These should be kobold names. A young kobold's given name is rarely more than a syllable or two. However, as they age, achieve status, and accomplish great deeds, kobolds add more syllables to their names, imitating a common draconic practice. Kobolds rarely have surnames except in an effort to better fit into a community, in which case they typically adopt the surname of an inspiring figure in that group.",
    data: [
      "**Azrnak** the Firebreather",
      "**Draahzin** the Clawed Menace",
      "**Enga** the Shadow Whisperer",
      "**Fazgyn** the Crystal Guardian",
      "**Fazij** the Tome Keeper",
      "**Jekkajak** the Tunnel Brute",
      "**Kib** the Silver Tailed",
      "**Kirrok** the Infernal Scale-bearer",
      "**Mirkol** the Gloom Watcher",
      "**Tarka** the Echo of Abyss",
      "**Urkak** the Cavern Chieftain",
      "**Varshez** the Eye of the Deep",
      "**Vroklan** the Scale-carved Warrior",
      "**Zekstikah** the Ember Seeker",
      "**Zgaz** the Fang of Underworld",
    ],
  },
  {
    category: "Ancestry",
    title: "Ratfolk",
    // image: icons.ratfolk,
    // icon: <GiRat size="1.3rem" />,
    instructions:
      "These should be ratfolk or ysoki names. Every ysoki family has perhaps two dozen names that have been passed down from generation to generation, sometimes with minor alterations or alternative nicknames. A grandfather might be Grivver, for example, while his daughter goes by Griva and her son is simply Griv. Ratfolk are often assigned nicknames and sobriquets by humanoids they interact with, but most ysoki find these names distasteful and endure them only when outside ysoki communities.",
    data: [
      "**Barnan** the Coinfinder",
      "**Chikis** the Shadowmancer",
      "**Chonan** the Silent Weaver",
      "**Deto** of the Twisted Tunnels",
      "**Jass** the Whispering Voice",
      "**Jix** Scavenger of the Beyond",
      "**Knagi** of the Hidden Laugh",
      "**Kubi** the Soulkeeper",
      "**Lolo** the Gleaming Eye",
      "**Ninnec** the Mysterious Enigma",
      "**Nos** the Long-Tailed Sage",
      "**Rak** the Bane of Rats",
      "**Renzi** the Wanderer of the Warrens",
      "**Skigim** the Dust Dancer",
      "**Tali** the Moon Seer",
      "**Zess** the Truth Sniffer",
    ],
  },
  {
    category: "Ancestry",
    title: "Tengu",
    // image: icons.tengu,
    // icon: <GiBirdClaw size="1.3rem" />,
    instructions:
      "These should be tengu names. Though roosted tengus tend toward more traditional names with the hard consonants often seen in the Tengu language, migrating tengus’ tendency to readily absorb and repurpose the culture of those around them has led to names that combine elements of whatever languages suited the namer’s fancy.",
    data: [
      "**Arkkak** the Wind Whisperer",
      "**Chuko** Keeper of the Silver Wind",
      "**Dolgra** the Storm Bearer",
      "**Dorodara** the Feathered Blade",
      "**Kakkariel** Shadow of the Mountain Peak",
      "**Kora** the Echo in the Mist",
      "**Marrak** Sentinel of the Silverpine",
      "**Mossarah** the Mystic Quill-Wielder",
      "**Pularrka** the Caw of Midnight",
      "**Rarorel** the Pretender",
      "**Ruk** the Silent Feather",
      "**Tak-Tak** the Ruby-Faced",
      "**Tsukotarra** Shield of the Crescent Moon",
    ],
  },
  {
    category: "Ancestry",
    title: "Vanara",
    // image: icons.vanara,
    // icon: <GiMonkey size="1.3rem" />,
    instructions:
      "These should be vanara names. Newborn vanaras aren't given names other than descriptors of their infant personalities or habits, like “Grip-Hand” or “Wailer.” When they learn to speak, vanaras are given another name based on important historical or mythological figures, or they're given the name of a specific ancestor they resemble in appearance or attitude (or whom their community hopes they'll grow to resemble). The chosen name usually contains consonants or vowels the young vanara frequently uses, as vanaras don't see a lot of use in giving someone a name they can't easily pronounce.",
    data: [
      "**Ashpaka** the Monkey Prince",
      "**Chichipi** Guardian of Jungle Mysteries",
      "**Haangeno** the Wise Sage",
      "**Hasa** the Laughing Trickster",
      "**Huanu** the Keeper of Ancient Secrets",
      "**Kana** the Silent Shadow",
      "**Nammem** the Vigil",
      "**Roprutu** Bearer of the Unseen Sword",
      "**Thathona** the Sacred Guardian",
      "**Unulu** the Whispering Wind",
      "**Vivatu** of the Ruby Orb",
    ],
  },
  {
    category: "Ancestry",
    title: "Anadi",
    //// image: icons.anadi,
    // icon: <GiSpiderWeb size="1.3rem" />,
    instructions:
      "These should be anadi names. Anadi names are given by the members of the web marriage that raised them. Each parent contributes a single syllable, usually the first, from their own name. Older anadi who feel their identity has settled often take on or are given a phrase-title to honor them as well. Anadi who live among human populations rarely take a cover name, but some might adopt one if their given name strongly contrasts the norm in the local culture.",
    data: [
      "**Altava** Weaver of Shadows",
      "**Anavachti** the Opulent Spinner",
      "Strings-On-The-River **Inkeelah**",
      "**Kerialnamu** the Orb Spinner of Destiny",
      "**Maracha** the Silk Tie of Souls",
      "Leaves-Shelter-Her-Feet **Naiala**",
      "**Orvasa** Harbinger of the Silk",
      "**Reloana** the Silken Matriarch",
      "Silk-Strong-As-Iron **Rivuken**",
      "**Velachamon** Weaver of the Ephemeral Web",
    ],
  },
  {
    category: "Ancestry",
    title: "Android",
    //// image: icons.android,
    // icon: <GiAndroidMask size="1.3rem" />,
    instructions:
      "These should be android names. Androids adopt the naming conventions of their surrounding societies, while those raised among their own kind instead select a single name that utilizes Androffan phonology. Occasionally, such androids add a numerical designation to their names, denoting how many generations their body has hosted life as a kind of homage to their bloodline.",
    data: [
      "**Anati** the Enchanted Automaton",
      "**Daniv** Lord of the Circuit",
      "**Era-4** the Timeless Mechanoid",
      "**Feralia** the Feral Machine",
      "**Gelegor** Guardian of the Iron Throne",
      "**Ilgos-5** the Fifth Sentinel",
      "**Koresh** Master of Hidden Codes",
      "**Oris** the Silent Cyborg",
      "**Prime** the Immortal Processor",
      "**Urdun** the Arcane Artificer",
    ],
  },
  {
    category: "Ancestry",
    title: "Automaton",
    //// image: icons.automaton,
    // icon: <GiVintageRobot size="1.3rem" />,
    instructions:
      "These should be automaton names. An automaton typically keeps the name they had before their transformation into a construct, if they can remember it. Even when other memories fade, memory of their name often remains. As such, many automatons have names with Jistkan origins. Second most common are automatons who had to give themselves a new name, as they lost their memories of the old one at some point. Those automatons that particularly believed in the cause of the Artificer Conclave might instead take the name of one of the conclave's members in honor of the cause that they gave their body to support. Some automatons prefer to change their names over their lifetimes, either selecting a new name from a culture they encountered or adding a title to represent a significant moment in their lives. In some cases an automaton will use a particularly cherished title in place of any other name.",
    data: [
      "**Alnhaman** the Stone Hearted",
      "**Busmin** Keeper of Forgotten Lore",
      "**The Doleful**",
      "**Enoh** the Time Bender",
      "**Himar** the Light Bringer",
      "**Kantral** Keeper of Sacred Oaths",
      "**The Kindred**",
      "**Numinar** the Voice of a Thousand Stars",
      "**Scholar** the Knowledge Seeker",
      "**Tehkis** the Web Weaver",
      "**Wayfarer** the Eternal Wanderer",
      "**Yulmian** the Silent Guardian",
    ],
  },
  {
    category: "Ancestry",
    title: "Conrasu",
    //// image: icons.conrasu,
    // icon: <GiChestArmor size="1.3rem" />,
    instructions:
      "These should be conrasu names. Conrasus have little in the way of consciousness as others understand it before they self-actualize and leave the nursery-towns where they sprouted. That includes a name, a concept of gender, and even the passage of time beyond their little bubbles—these are picked up in the wider world. As a result, a conrasu might have nearly any appellation.",
    data: [
      "**Automa** the Starseed Artisan",
      "**Azubu** Harbinger of Celestial Cadence",
      "**Dumi** the Silent Resonance",
      "**Emeka** Architect of Conduits",
      "**Ganizadi** Guardian of Harmony",
      "**Locu** Echo within the Universe's Loom",
      "**Incanes** the Timeless Enigma",
      "**Radi** Weaver of Light",
      "**Shell** Sculptor of the Æther",
      "**Weave** Choreographer of Starlight Patterns",
    ],
  },
  {
    category: "Ancestry",
    title: "Fleshwarp",
    //// image: icons.fleshwarp,
    // icon: <GiRaiseZombie size="1.3rem" />,
    instructions:
      "These should be fleshwarp names. Fleshwarps can come from—and thus have names from—any culture or ancestry, but some give themselves new names after being transformed, whether to celebrate the change, recognize a new phase of their lives, or conceal their past identity. Many fleshwarps also carry a descriptive nickname granted to them by others, such as “Triple Handed,” “Barkfoot,” or “Many-Mouth.” Fleshwarps don't keep nicknames they find personally offensive, but they tend to keep ones that describe their distinctive appearances or that are given by people they care about.",
    data: [
      "**Borble** the Triple Handed",
      "**Dag** Keeper of Whispers",
      "**Feff** the Silent Eruption",
      "**Hurn** the Twisted Seer",
      "**Kemp** Barkfoot",
      "**Omber** the Shallow Depths",
      "**Ostro** the Wandering Star",
      "**Shurni** the Whispering Echo",
      "**Surm** the Many-Mouth",
      "**Wumpin** the Timeworn Stone",
    ],
  },
  {
    category: "Ancestry",
    title: "Ghoran",
    //// image: icons.ghoran,
    // icon: <GiPlantsAndAnimals size="1.3rem" />,
    instructions:
      "These should be ghoran names. Most ghorans pick a new name with each incarnation, usually selecting a name or concept that they found pleasing in a past life. Occasionally, a ghoran might reuse a name for several incarnations in a row, especially if remaining in a community of other peoples, though each incarnation is still a distinct person.",
    data: [
      "**Amsalu** the Forest Whisperer",
      "**Ash** the Ember Soul",
      "**Emnet** the Resilience of Life",
      "**Sieri** the Blossom Seer",
      "**Ooniel** the Unseen Guardian",
      "**Arshmarish** the Rooted Sage",
      "**Velt** the Verdant Heart",
      "**Delphinium** the Lustrous Bloom",
      "**Hach** the Silent Stalk",
      "**Emerald** the Enchanted Leaf",
      "**Sable** the Shade of Nightshade",
    ],
  },
  {
    category: "Ancestry",
    title: "Goloma",
    //// image: icons.goloma,
    // icon: <PiHorseFill size="1.3rem" />,
    instructions:
      "These should be goloma names. A goloma's true name is kept among golomas, as there are hundreds of cautionary tales of what could happen if another creature learns a goloma's true name. Names tend to lack soft syllables, which golomas often struggle to pronounce, and typically consist of hard consonants and individually enunciated vowels instead. Among other people, golomas tend to use names that are intended to be intimidating, taking elements and sounds from Aklo, Necril, or words from local languages that seem to cause strong reactions.",
    data: [
      "**Biqkuul** the Silvan Phantom",
      "**Ehbouja** the Timber-faced Horror",
      "**Haamaah** the Many-Eyed Marauder",
      "**Kouzo** Warden of the Woodland Shadows",
      "**Quaerjii** the Grove Ghoul",
      "**Tebaazu** the Enigma of Elms",
      "**Uruueda** the Forest's Mystifying Fear",
      "**Zekuukeu** the Vale-Eyed Stalker",
    ],
  },
  {
    category: "Ancestry",
    title: "Kashrishi",
    //// image: icons.kashrishi,
    // icon: <GiRhinocerosHorn size="1.3rem" />,
    instructions:
      "These should be kashrishi names. The empathic sense of a kashrishi has its own “mental fingerprint” that's unique to each member of the species, and this mental fingerprint can be conveyed through psychic communications as a name. Kashrishi who adventure with non-kashrishi often adopt descriptive names that their companions can more easily speak and remember.",
    data: [
      "**Climber** the Peaks' Whisperer",
      "**Firehorn** the Inferno Warden",
      "**Guardian** the Sentinel of Empathic Shields",
      "**Healer** the Harmoniser of Ailments",
      "**Lantern** the Luminary of Hidden Paths",
      "**Mother** the Beacon of Life's Tapestry",
      "**Scout** the Seer of Unseen Trails",
      "**Softhand** the Conduit of Gentle Touches",
      "**Tempest** the Stormshaper of Fates",
      "**Warrior** the Vanguard of Resilient Spirits",
    ],
  },
  {
    category: "Ancestry",
    title: "Poppet",
    //// image: icons.poppet,
    // icon: <GiVoodooDoll size="1.3rem" />,
    instructions:
      "These should be poppet names. Poppets generally choose their own names, usually descriptive nicknames based on their materials, patterns, size, or demeanor. They tend to pick up and shed nicknames throughout their lives, and they happily adopt nicknames given to them by people they like. A poppet fashioned to look like a particular person, such as a doll sewn to resemble a deceased child, might proudly take the name of that person.",
    data: [
      "**Burlap** the Child's Guardian",
      "**Buttoneyes** the Watcher of Realms",
      "**Checker** the Guardian of the Hearth",
      "**Clockwhirr** the Living Timepiece",
      "**Fivestitch** the Seer of Fates",
      "**Nettle** the Bringer of Courage",
      "**Scramble** the Spirit of Mischief",
      "**Stuffing** the Heart of Comfort",
      "**Taffeta** the Enchantress of Elegance",
      "**Tattercap** the Guardian of Lost Things",
    ],
  },
  {
    category: "Ancestry",
    title: "Shisk",
    //// image: icons.shisk,
    // icon: <GiPorcupine size="1.3rem" />,
    instructions:
      "These should be shisk names. Shisk names are usually granted by their parents, though these names often have secret meanings known only to their families. They are often filled with sibilant syllables, occasionally punctuated by sharp vowels.",
    data: [
      "**Adomssha** the Bringer of Obscure Truths",
      "**Asjossa** the Silent Whisperer of Mountain Shadows",
      "**Chishinsa** the Benevolent Keeper of Forbidden Wisdom",
      "**Dalissho** the Solitary Wanderer in Midnight Tunnels",
      "**Lessia** the Harbinger of Secretive Echos",
      "**Lishassha** the Guardian of Arcane Knowledge",
      "**Somissu** the Clandestine Chronicler of the Underearth",
      "**Quinshu** the Relic Reaper of the Inter-darkness",
    ],
  },
  {
    category: "Ancestry",
    title: "Shoony",
    //// image: icons.shoony,
    // icon: <PiDogFill size="1.3rem" />,
    instructions:
      "These should be shoony names. With their strong family values and emphasis on found friends, it’s no wonder that shoonies take particular pride in naming their children after other loved ones. Shoony names are short, guttural, and often sound like loose strings of unassociated vowels and soft consonants to people of other ancestries. Shoonies value names and take great care to learn and speak the correct pronunciations of their friends’ names.",
    data: [
      "**Ahogo** the Peaceful Artisan",
      "**Arnbin** the Diplomatic Watchman",
      "**Bighmor** the Tenacious Craftsman",
      "**Bondin** the Resilient Philosopher",
      "**Domwurd** the Enduring Negotiator",
      "**Ebmeur** the Industrious Guardian",
      "**Gopor** the Assiduous Diplomat",
      "**Gurna** the Persistent Ambassador",
      "**Hiemgur** the Stubborn Defender",
      "**Mufurlo** the Resourceful Trader",
      "**Oriog** the Sturdy Peacemaker",
      "**Pulumar** the Steadfast Builder",
      "**Raliamar** the Tireless Mediator",
      "**Ruggion** the Doughty Advocate",
      "**Uhulrig** the Staunch Pacifist",
      "**Ungrin** the Relentless Worker",
    ],
  },
  {
    category: "Ancestry",
    title: "Skeleton",
    //// image: icons.skeleton,
    // icon: <GiSkeletalHand size="1.3rem" />,
    instructions:
      "These should be skeleton names. No widespread naming convention exists for skeletons. When necromancers bother to name skeletons they've raised, they typically choose names that suit their own tastes, the way one would name a pet. Others might be named for their role or job. Skeletons with their memories intact might choose to keep their name from when they were alive, but others might choose new names based on their undead experiences.",
    data: [
      "**Clatterjaw** the Bones of Discord",
      "**Creaker** the Whispering Contemplator",
      "**Doorstop** the Halted Guardian of Realms",
      "**Final Sacrifice** the Last Martyr of Death",
      "**Gochiyo** the Eerily Silent Warlock",
      "**Lectern** the Stoic Oracle of Fate",
      "**Macefodder** the Forlorn Shield in Eternal Battle",
      "**Sixth Lancer** the Spectral Harbinger of War",
      "**Skulldyr** the Skulllord of Dark Corruption",
      "**Xelim** the Ancient Magister of Decay",
    ],
  },
  {
    category: "Ancestry",
    title: "Sprite",
    //// image: icons.sprite,
    // icon: <GiFairy size="1.3rem" />,
    instructions:
      "These should be sprite or fairy names. Sprite names are based entirely on their parents' whimsy. Sprites often adopt additional monikers later in life or change those assigned to them at birth; this is neither frowned upon nor considered abnormal.",
    data: [
      "**Bree** the Whisper of the Thorned Willow",
      "**Plumgrass** Healer of the Midnight Meadow",
      "**Cowrie** the Small but Mighty",
      "**Flit** the Fluttering Flame of the Silver Woods",
      "**Moth** the Enchanting Specter of the Moonlit Shadows",
      "**Zephyr** Carver of the Celestial Breeze",
      "**Naatalu** the Benevolent",
      "**Pinebrush** Sentinel of the Evergreen Eternity",
      "**Zandivar** Maestro of the Stardust Symphony",
    ],
  },
  {
    category: "Ancestry",
    title: "Strix",
    //// image: icons.strix,
    // icon: <GiLibertyWing size="1.3rem" />,
    instructions:
      "These should be strix names. Strix names consist of sounds that are reminiscent of chirping, screeches, or trilling by various birds, and their naming conventions are influenced primarily by tradition and spirituality. Strix in small communities might share a common syllable among all their names to express their unity. Due to their deep affection for their family members, naming children after other loved ones is very common, occasionally with an additional syllable or slight change to the pronunciation.",
    data: [
      "**Chiit-iir** the Whisperer of Shadows",
      "**Cicreeti** the Storm's Songstress",
      "**Ikatarii** the Flames of Destiny",
      "**Irkoata** Holder of the Mystic Orb",
      "**Kaata** the Midnight Wanderer",
      "**Kiilo** the Spirit Whisperer",
      "**Kirii** the Starforged Warrior",
      "**Rahka** Queen of the Silver Sands",
      "**Roatatwiil** the Tyrant of Lost Realms",
      "**Turiilo** the Bringer of Tranquil Seas",
      "**Turuk** the Skybound Titan",
      "**Twilii** the Dance of the Moonlight",
    ],
  },
  {
    category: "Ancestry",
    title: "Vishkanya",
    //// image: icons.vishkanya,
    // icon: <GiPoison size="1.3rem" />,
    instructions:
      "These should be vishkanya names. Vishkanyan names often include short vowel sounds in the middle of the name, with a large number of fricative consonants pronounced most accurately with a forked tongue. Names are often chosen from momentous events in vishkanyan history or from matters related to the maternal line of the child. When they go through significant life events, vishkanyas may choose new names for themselves, and many often do so multiple times. Each name represents an important part of the individual's story—who they were, and who they have become.",
    data: [
      "**Ashath** Venom's Whisper",
      "**Casuthis** of Guiding Hands",
      "**Enysi** Shadow of the Serpent Star",
      "**Izith** the Jade Fang",
      "**Othasee** the Aurora Adder",
      "Riddle of **Esaviz**",
      "**Salthazar** Crimson Coil",
      "**Thasi** the Ragebreaker",
    ],
  },
];
