/*
pg. 433
Precise Senses
Average vision is a precise sense—a sense that can be used to perceive the world in nuanced detail. The only way to target a creature without having drawbacks is to use a precise sense. You can usually detect a creature automatically with a precise sense unless that creature is hiding or obscured by the environment, in which case you can use the Seek basic action to better detect the creature.
Imprecise Senses
Average hearing is an imprecise sense—it can’t detect the full range of detail that a precise sense can. You can usually sense a creature automatically with an imprecise sense, but it has the hidden condition instead of the observed condition. It might be undetected by you if it’s using Stealth or is in an environment that distorts the sense, such as a noisy room in the case of hearing. In those cases, you have to use the Seek basic action to detect the creature. At best, an imprecise sense can be used to make an undetected creature (or one you didn’t even know was there) merely hidden—it can’t make the creature observed.
Vague Senses
A character also has many vague senses—ones that can alert you that something is there but aren’t useful for zeroing in on it to determine exactly what it is. The most useful of these for a typical character is the sense of smell. At best, a vague sense can be used to detect the presence of an unnoticed creature, making it undetected. Even then, the vague sense isn’t sufficient to make the creature hidden or observed.
When one creature might detect another, the GM almost always uses the most precise sense available.
Pathfinder’s rules assume that a given creature has vision as its only precise sense and hearing as its only imprecise sense. Some characters and creatures, however, have precise or imprecise senses that don’t match this assumption. For instance, a character with poor vision might treat that sense as imprecise, an animal with the scent ability can use its sense of smell as an imprecise sense, and a creature with echolocation or a similar ability can use hearing as a precise sense. Such senses are often given special names and appear as “echolocation (precise),” “scent (imprecise) 30 feet,” etc.
*/
