import assert from 'node:assert/strict';
import { after, test } from 'node:test';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const root = fileURLToPath(new URL('../', import.meta.url));
const require = createRequire(`${root}/package.json`);
const { build } = require('esbuild');
const ts = require('typescript');
const { QueryClient, QueryObserver } = require('@tanstack/react-query');
const directory = await mkdtemp(join(tmpdir(), 'wg-item-spell-dependencies-'));
after(() => rm(directory, { recursive: true, force: true }));

// Substitute remote content and notifications, retaining the real spell parser.
const contentSource = await readFile(join(root, 'src/process/content/content-store.ts'), 'utf8');
const contentExports = [...contentSource.matchAll(/export (?:async )?function ([A-Za-z0-9_]+)/g)].map(
  (match) => match[1]
);
const output = join(directory, 'item-spells.mjs');
await build({
  absWorkingDir: root,
  stdin: {
    contents: `export {detectSpells, detectSpellheartSpells} from '@spells/spell-utils'; export {ItemSchema, InventoryItemSchema, ContentSourceSchema} from '@schemas/content'; export * from '@spells/item-spell-dependencies';`,
    resolveDir: root,
    loader: 'ts',
  },
  tsconfig: join(root, 'tsconfig.json'),
  bundle: true,
  write: false,
  platform: 'node',
  format: 'esm',
  define: { 'import.meta.env': JSON.stringify({ VITE_ENV: 'production' }) },
  plugins: [
    {
      name: 'item-spell-system-boundaries',
      setup(builder) {
        builder.onResolve({ filter: /^@content\/content-store$/ }, () => ({ path: 'content', namespace: 'boundary' }));
        builder.onResolve({ filter: /^@utils\/notifications$/ }, () => ({
          path: 'notifications',
          namespace: 'boundary',
        }));
        builder.onLoad({ filter: /.*/, namespace: 'boundary' }, ({ path }) => ({
          contents:
            path === 'content'
              ? contentExports
                  .map((name) =>
                    name === 'fetchContent'
                      ? 'export function fetchContent(...args) { return globalThis.__itemSpellFetch(...args); }'
                      : `export function ${name}() { return []; }`
                  )
                  .join('\n')
              : 'export function displayError() {}',
          loader: 'ts',
        }));
      },
    },
  ],
}).then((bundle) => writeFile(output, bundle.outputFiles[0].text));
const {
  detectSpells,
  detectSpellheartSpells,
  getInventorySpellIds,
  getMissingSpellIds,
  getExplicitSpellQueryOptions,
  mergeSpellDependencies,
  filterSpellCatalog,
  resolveItemSpellRead,
  ItemSchema,
  InventoryItemSchema,
  ContentSourceSchema,
} = await import(pathToFileURL(output));

// Actual historical and current catalog rows, not values generated by the resolver.
const completionSql = await readFile(
  join(root, '../supabase/migrations/20261002100000_treasure_vault_complete_catalog.sql'),
  'utf8'
);
const completionParts = completionSql.split('$completion100$');
assert.equal(completionParts.length, 3);
const completion = JSON.parse(completionParts[1]);
const ashPatch = completion.patches.find((row) => row.table === 'item' && row.id === 12695);
const ashCanonical = ItemSchema.parse(ashPatch.final);
const treasureVault = ContentSourceSchema.parse(completion.sources.find((row) => row.id === 16).final);
const disintegrate = completion.dependencies.find((row) => row.table === 'spell' && row.id === 4571).anchor;
const savedAsh = InventoryItemSchema.parse(
  JSON.parse(
    JSON.stringify({
      id: 'saved-ash',
      item: ItemSchema.parse(ashPatch.anchor),
      is_formula: false,
      is_equipped: true,
      is_invested: false,
      is_implanted: false,
      container_contents: [],
    })
  )
);

test('a schema-roundtripped saved Ash Puppet resolves only its already explicit Disintegrate reference', () => {
  assert.equal(Object.hasOwn(savedAsh.item, 'uuid'), false);
  assert.equal(Object.hasOwn(ashCanonical, 'uuid'), false);
  assert.deepEqual(getInventorySpellIds([savedAsh]), []);
  const before = structuredClone(savedAsh);
  const read = resolveItemSpellRead(savedAsh.item, ashCanonical, treasureVault);
  assert.equal(read.recoveredLegacyReference, true);
  assert.deepEqual(getInventorySpellIds([savedAsh], new Map([[savedAsh, read]])), [4571]);
  assert.deepEqual(
    detectSpells(read.description, [disintegrate], true).map(({ spell, rank }) => [spell.id, rank]),
    [[4571, 6]]
  );
  assert.equal(
    read.description,
    savedAsh.item.description.replace('\\[\\[Disintegrate\\]\\]', '[Disintegrate](link_spell_4571)')
  );
  assert.equal(read.description.includes('**Frequency**'), false);
  assert.deepEqual(savedAsh, before);
});

test('Ash recovery rejects changed snapshots, unofficial counterparts and ambiguous spell targets', () => {
  const unchanged = (item, ...overrides) => {
    const canonical = overrides.length > 0 ? overrides[0] : ashCanonical;
    const source = overrides.length > 1 ? overrides[1] : treasureVault;
    const before = structuredClone({ item, canonical, source });
    assert.deepEqual(resolveItemSpellRead(item, canonical, source), {
      description: item.description,
      recoveredLegacyReference: false,
    });
    assert.deepEqual({ item, canonical, source }, before);
  };
  for (const [field, value] of [
    ['id', 12696],
    ['content_source_id', 3],
    ['created_at', '2024-04-19T04:25:49.043178+00:00'],
    ['name', 'Custom Ash Puppet'],
    ['level', 15],
    ['group', 'WEAPON'],
    ['description', `${savedAsh.item.description}\nCustom casting rule.`],
    ['description', savedAsh.item.description.replace('\\[\\[Disintegrate\\]\\]', '[Disintegrate](link_spell_1)')],
  ]) {
    unchanged({ ...savedAsh.item, [field]: value });
    unchanged(savedAsh.item, { ...ashCanonical, [field]: value });
  }
  unchanged(savedAsh.item, undefined);
  unchanged(savedAsh.item, ashCanonical, { ...treasureVault, id: 3 });
  unchanged(savedAsh.item, ashCanonical, { ...treasureVault, user_id: 'homebrew-owner' });
  unchanged(savedAsh.item, ashCanonical, { ...treasureVault, is_published: false });
  unchanged(savedAsh.item, ashCanonical, undefined);
  unchanged(savedAsh.item, {
    ...ashCanonical,
    description: ashCanonical.description.replace('(link_spell_4571)', '(link_spell_1)'),
  });
  unchanged(savedAsh.item, {
    ...ashCanonical,
    description: `${ashCanonical.description}\n**Effect** You cast [Disintegrate](link_spell_4571).`,
  });
  for (const id of [12326, 12337]) {
    const patch = completion.patches.find((row) => row.table === 'item' && row.id === id);
    unchanged(ItemSchema.parse(patch.anchor), ItemSchema.parse(patch.final));
  }
});

// Execute the actual memo and mount-effect bodies without replacing the real parser or inventory setter.
const extractSource = async (path) => {
  const text = await readFile(join(root, path), 'utf8');
  const file = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const nodes = [];
  const visit = (node) => {
    nodes.push(node);
    ts.forEachChild(node, visit);
  };
  visit(file);
  return { text, file, nodes };
};
const evaluateSource = (source, node, bindings, result) => {
  const printed = ts
    .createPrinter()
    .printNode(ts.EmitHint.Unspecified, node, source.file)
    .replace(/^export /m, '');
  const javascript = ts.transpileModule(printed, {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  }).outputText;
  return new Function(...Object.keys(bindings), `${javascript}\nreturn ${result};`)(...Object.values(bindings));
};
const variableStatement = (source, name) => {
  const matches = source.nodes.filter(
    (node) =>
      ts.isVariableStatement(node) &&
      node.declarationList.declarations.some((entry) => entry.name.getText(source.file) === name)
  );
  assert.equal(matches.length, 1, `${name}: exactly one actual declaration`);
  return matches[0];
};
const wandSource = await extractSource('src/pages/character_sheet/panels/spells_list/WandSpellsList.tsx');
const panelSource = await extractSource('src/pages/character_sheet/panels/SpellsPanel.tsx');
const handlerSource = await extractSource('src/process/items/inv-handlers.tsx');
const chargeHandler = evaluateSource(
  handlerSource,
  variableStatement(handlerSource, 'handleUpdateItemCharges'),
  {},
  'handleUpdateItemCharges'
);
const wandEffect = wandSource.nodes.filter(
  (node) =>
    ts.isExpressionStatement(node) &&
    ts.isCallExpression(node.expression) &&
    node.expression.expression.getText(wandSource.file) === 'useEffect'
);
assert.equal(wandEffect.length, 1, 'exactly one actual wand mount effect');
const mountWands = (entries, reads) => {
  let entity = { inventory: { items: entries }, unchanged: { saved: true } };
  let writes = 0;
  const props = {
    wands: entries,
    allSpells: [disintegrate],
    itemSpellReads: reads,
    setEntity: (update) => {
      writes++;
      entity = update(entity);
    },
  };
  const processedWands = evaluateSource(
    wandSource,
    variableStatement(wandSource, 'processedWands'),
    { props, detectSpells, useMemo: (callback) => callback() },
    'processedWands'
  );
  evaluateSource(
    wandSource,
    wandEffect[0],
    { props, processedWands, handleUpdateItemCharges: chargeHandler, useEffect: (callback) => callback() },
    'undefined'
  );
  return {
    processedWands,
    props,
    get entity() {
      return entity;
    },
    get writes() {
      return writes;
    },
  };
};

test('actual wand memo and mount effect recover saved Ash without writing charges on mount or remount', () => {
  const before = structuredClone(savedAsh);
  const read = resolveItemSpellRead(savedAsh.item, ashCanonical, treasureVault);
  for (let mount = 0; mount < 2; mount++) {
    const result = mountWands([savedAsh], new Map([[savedAsh, read]]));
    assert.deepEqual(
      result.processedWands.map((wand) => [wand.spell.spell.id, wand.spell.rank]),
      [[4571, 6]]
    );
    assert.equal(result.processedWands[0].item, savedAsh, 'original inventory entry retained');
    assert.deepEqual(result.processedWands[0].charges, { current: 0, max: 1 });
    assert.equal(result.writes, 0, 'no mount charge initialization');
    assert.deepEqual(result.entity.inventory.items, [before]);
  }
  assert.deepEqual(savedAsh, before);
});

test('wand charge defaults preserve explicit saved values and ordinary initialization', () => {
  for (const charges of [
    { current: 2, max: 3 },
    { current: 0, max: 0 },
  ]) {
    const entry = { ...savedAsh, item: { ...savedAsh.item, meta_data: { ...savedAsh.item.meta_data, charges } } };
    const result = mountWands(
      [entry],
      new Map([[entry, resolveItemSpellRead(entry.item, ashCanonical, treasureVault)]])
    );
    assert.deepEqual(result.processedWands[0].charges, charges);
    assert.equal(result.writes, 0);
    assert.deepEqual(result.entity.inventory.items, [entry]);
  }
  const ordinary = { ...savedAsh, item: ashCanonical };
  const result = mountWands([ordinary]);
  assert.equal(result.writes, 1, 'ordinary wand retains existing max-charge initialization');
  assert.equal(result.entity.inventory.items[0].item.meta_data.charges.max, 1);
  assert.equal(ordinary.item.meta_data?.charges, undefined);
});

test('actual recovered wand cast uses the display default and only persists the requested spent charge', () => {
  const mounted = mountWands(
    [savedAsh],
    new Map([[savedAsh, resolveItemSpellRead(savedAsh.item, ashCanonical, treasureVault)]])
  );
  const attributes = wandSource.nodes.filter(
    (node) => ts.isJsxAttribute(node) && node.name.getText(wandSource.file) === 'onCastSpell'
  );
  assert.equal(attributes.length, 1, 'exactly one actual wand casting callback');
  const expression = attributes[0].initializer.expression.getText(wandSource.file);
  const javascript = ts.transpileModule(`const cast = ${expression};`, {
    fileName: 'wand-cast.tsx',
    compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, jsx: ts.JsxEmit.React },
  }).outputText;
  const cast = new Function('props', 'wand', 'handleUpdateItemCharges', 'modals', `${javascript}\nreturn cast;`)(
    mounted.props,
    mounted.processedWands[0],
    chargeHandler,
    { openConfirmModal: () => assert.fail('the first saved Ash cast must not require overcharging') }
  );
  cast(true);
  assert.equal(mounted.writes, 1);
  const expected = structuredClone(savedAsh);
  expected.item.meta_data = { ...expected.item.meta_data, charges: { current: 1, max: undefined } };
  assert.deepEqual(mounted.entity.inventory.items, [expected]);
  assert.equal(savedAsh.item.meta_data?.charges, undefined);
});

test('actual spell panel shares reactive official indexing text with dependency reads and the wand list', () => {
  const evaluatePanel = (items, sources, entries = [savedAsh]) => {
    const props = { content: { items, sources, spells: [] }, entity: { inventory: { items: entries } } };
    const itemSpellReads = evaluateSource(
      panelSource,
      variableStatement(panelSource, 'itemSpellReads'),
      {
        props,
        useMemo: (callback, dependencies) => {
          assert.deepEqual(dependencies, [props.content.items, props.content.sources, props.entity.inventory]);
          return callback();
        },
        resolveItemSpellRead,
      },
      'itemSpellReads'
    );
    const missing = evaluateSource(
      panelSource,
      variableStatement(panelSource, 'missingItemIds'),
      { props, itemSpellReads, useMemo: (callback) => callback(), getMissingSpellIds, getInventorySpellIds },
      'missingItemIds'
    );
    return { itemSpellReads, missing };
  };
  const loading = evaluatePanel([], []);
  assert.deepEqual(loading.missing, []);
  assert.equal(loading.itemSpellReads.get(savedAsh).recoveredLegacyReference, false);
  const active = evaluatePanel([ashCanonical], [treasureVault]);
  assert.deepEqual(active.missing, [4571]);
  assert.deepEqual(
    mountWands([savedAsh], active.itemSpellReads).processedWands.map((wand) => wand.spell.spell.id),
    [4571]
  );
  for (const [items, sources] of [
    [[], [treasureVault]],
    [[ashCanonical], []],
  ]) {
    const disabled = evaluatePanel(items, sources);
    assert.deepEqual(disabled.missing, []);
    assert.deepEqual(mountWands([savedAsh], disabled.itemSpellReads).processedWands, []);
  }
  const custom = { ...savedAsh, item: { ...savedAsh.item, description: `${savedAsh.item.description}\nCustom.` } };
  const duplicateIds = evaluatePanel([ashCanonical], [treasureVault], [savedAsh, custom]);
  assert.equal(duplicateIds.itemSpellReads.size, 2);
  assert.equal(duplicateIds.itemSpellReads.get(savedAsh).recoveredLegacyReference, true);
  assert.equal(duplicateIds.itemSpellReads.get(custom).recoveredLegacyReference, false);
  const lists = panelSource.nodes.filter(
    (node) => ts.isJsxSelfClosingElement(node) && node.tagName.getText(panelSource.file) === 'SpellList'
  );
  const listAttributes = (type) => {
    const matches = lists.filter((node) =>
      node.attributes.properties.some(
        (attribute) =>
          ts.isJsxAttribute(attribute) &&
          attribute.name.getText(panelSource.file) === 'type' &&
          ts.isStringLiteral(attribute.initializer) &&
          attribute.initializer.text === type
      )
    );
    assert.equal(matches.length, 1, `${type}: exactly one actual item list`);
    return new Map(
      matches[0].attributes.properties
        .filter(ts.isJsxAttribute)
        .map((attribute) => [
          attribute.name.getText(panelSource.file),
          attribute.initializer?.getText(panelSource.file),
        ])
    );
  };
  assert.equal(listAttributes('WAND').get('itemSpellReads'), '{itemSpellReads}');
  assert.equal(listAttributes('SPELLHEART').get('canonicalItems'), '{props.content.items}');
  assert.equal(listAttributes('SPELLHEART').get('contentSources'), '{props.content.sources}');
});

const petalStorm = { id: 8999, name: 'Petal Storm', rank: 4, cast: 'TWO-ACTIONS', content_source_id: 842 };
const elementalAbsorption = {
  id: 8867,
  name: 'Elemental Absorption',
  rank: 3,
  cast: 'TWO-ACTIONS',
  content_source_id: 842,
};
const localSpell = { id: 1, name: 'Local spell', rank: 1, cast: 'ONE-ACTION', content_source_id: 16 };
const boreal = {
  id: 'boreal',
  is_equipped: true,
  is_formula: false,
  is_invested: false,
  container_contents: [],
  item: {
    id: 11794,
    name: 'Boreal Staff',
    group: 'WEAPON',
    traits: [1546],
    meta_data: {},
    description: '* **3rd** [elemental absorption](link_spell_8867) ([water](link_trait_1584) only)',
  },
};
const brightbloom = {
  id: 'brightbloom',
  is_equipped: false,
  is_formula: false,
  is_invested: false,
  container_contents: [],
  item: {
    id: 11814,
    name: 'Brightbloom Posy (Major)',
    group: 'GENERAL',
    traits: [2570],
    meta_data: {},
    description: '**Effect** You cast 6th-rank [petal storm](link_spell_8999).',
  },
};

test('Treasure Vault item references recover their exact spells without enabling Impossible Magic for selection', () => {
  // With only source16 loaded, the original detector omits both missing dependencies.
  assert.deepEqual(detectSpells(boreal.item.description, [localSpell]), []);
  assert.deepEqual(detectSpells(brightbloom.item.description, [localSpell], true), []);
  const refs = getInventorySpellIds([boreal, brightbloom]);
  assert.deepEqual(refs, [8867, 8999]);
  const missing = getMissingSpellIds([localSpell], refs);
  const itemCatalog = mergeSpellDependencies([localSpell], [elementalAbsorption, petalStorm], missing);
  assert.deepEqual(
    detectSpells(boreal.item.description, itemCatalog).map(({ spell, rank }) => [spell.id, rank]),
    [[8867, 3]]
  );
  assert.deepEqual(
    detectSpells(brightbloom.item.description, itemCatalog, true).map(({ spell, rank }) => [spell.id, rank]),
    [[8999, 6]]
  );
  assert.deepEqual(
    [localSpell].map((spell) => spell.id),
    [1]
  );
});

test('Major Brightbloom Posy casts its explicitly sixth-rank Petal Storm without changing the catalog spell', () => {
  const text =
    '**Activate** Cast a Spell; **Frequency** once per day; **Effect** You cast 6th-rank [petal storm](link_spell_8999).';
  const detected = detectSpells(text, [petalStorm], true);
  assert.equal(detected.length, 1);
  assert.equal(detected[0].rank, 6);
  assert.equal(detected[0].spell.rank, 6);
  assert.equal(petalStorm.rank, 4);
});

test('spellhearts expose each casting activation, not armor benefits or descriptive comparisons', () => {
  const speakWithPlants = { ...localSpell, id: 4848, name: 'Speak With Plants', rank: 3 };
  const tangleVine = { ...localSpell, id: 4888, name: 'Tangle Vine', rank: 0 };
  const soothingBlossoms = { ...localSpell, id: 8836, name: 'Soothing Blossoms', rank: 2 };
  const burningBlossoms = { ...localSpell, id: 5137, name: 'Burning Blossoms', rank: 7 };
  const text = [
    '**Armor** You speak with flowers, as [speak with plants](link_spell_4848).',
    '**Activate** [Cast a Spell](link_action_19611); **Effect** You cast [tangle vine](link_spell_4888).',
    '**Activate** [Cast a Spell](link_action_19611); **Frequency** once per day; **Effect** You cast [soothing blossoms](link_spell_8836).',
    '**Activate** [Cast a Spell](link_action_19611); **Frequency** once per day; **Effect** You cast 6th-rank [petal storm](link_spell_8999). This resembles [speak with plants](link_spell_4848).',
    '**Activate** [Cast a Spell](link_action_19611); **Frequency** once per day; **Effect** You cast [burning blossoms](link_spell_5137).',
  ].join('\n\n');
  const catalog = [speakWithPlants, tangleVine, soothingBlossoms, petalStorm, burningBlossoms];
  assert.deepEqual(
    detectSpellheartSpells(text, catalog).map(({ spell, rank }) => [spell.id, spell.rank, rank]),
    [
      [4888, 0, 0],
      [8836, 2, 2],
      [8999, 6, 6],
      [5137, 7, 7],
    ]
  );
  assert.deepEqual(
    detectSpellheartSpells(text, [petalStorm]).map(({ spell, rank }) => [spell.id, rank]),
    [[8999, 6]]
  );
  assert.equal(petalStorm.rank, 4);
});

test('spellheart casting handles legacy multiline activations and shared alternative ranks locally', () => {
  const harm = { ...localSpell, id: 4653, name: 'Harm', rank: 1 };
  const heal = { ...localSpell, id: 4656, name: 'Heal', rank: 1 };
  const text = [
    '**Activate** Cast a Spell\n\n**Effect** You cast 4th-level *[harm](link_spell_4653)* or *[heal](link_spell_4656)*.',
    '**Activate** [Cast a Spell;](link_action_19611) **Effect** You cast [heal](link_spell_4656).',
    '**Activate** Cast a Spell; **Effect** You cast a 3rd-rank [harm](link_spell_4653) or 6th-rank [petal storm](link_spell_8999).',
  ].join('\n\n');
  assert.deepEqual(
    detectSpellheartSpells(text, [harm, heal, petalStorm]).map(({ spell, rank }) => [spell.id, rank]),
    [
      [4653, 4],
      [4656, 4],
      [4656, 1],
      [4653, 3],
      [8999, 6],
    ]
  );
  assert.deepEqual(
    detectSpellheartSpells(text, [heal]).map(({ spell, rank }) => [spell.id, rank]),
    [
      [4656, 4],
      [4656, 1],
    ]
  );
  assert.equal(heal.rank, 1);
});

test('spellheart passive references and noncasting activations are never presented as spells', () => {
  const text = [
    '**Armor** After you cast a spell, the item casts [petal storm](link_spell_8999) on you.',
    '**Activate** Interact; **Effect** You gain a benefit as [petal storm](link_spell_8999).',
    '**Activate** Interact; **Requirements** You have cast [petal storm](link_spell_8999).',
  ].join('\n\n');
  assert.deepEqual(detectSpellheartSpells(text, [petalStorm]), []);
});

test('spellheart comma-separated casting alternatives retain every explicit and shared rank', () => {
  const harm = { ...localSpell, id: 4653, name: 'Harm', rank: 1 };
  const heal = { ...localSpell, id: 4656, name: 'Heal', rank: 1 };
  const catalog = [harm, heal, petalStorm];
  const original = structuredClone(catalog);
  for (const verb of ['cast', '[cast](link_action_19611)']) {
    for (const conjunction of ['or', 'and']) {
      const text = `**Activate** Cast a Spell; **Effect** You ${verb} a 4th-rank *[harm](link_spell_4653)*, *[heal](link_spell_4656)*, ${conjunction} 6th-rank *[petal storm](link_spell_8999)*. You ${verb} 4th-rank [heal](link_spell_4656).`;
      assert.deepEqual(
        detectSpellheartSpells(text, catalog).map(({ spell, rank }) => [spell.id, spell.rank, rank]),
        [
          [4653, 4, 4],
          [4656, 4, 4],
          [8999, 6, 6],
        ],
        `${verb}: comma + ${conjunction}`
      );
    }
  }
  assert.deepEqual(catalog, original, 'Casting alternatives cannot heighten catalog rows');
});

test('spellheart code examples do not grant casts or hide the real following activation', () => {
  const shield = { ...localSpell, id: 4831, name: 'Shield', rank: 0 };
  const heal = { ...localSpell, id: 4656, name: 'Heal', rank: 1 };
  const catalog = [shield, heal];
  for (const verb of ['cast', '[cast](link_action_19611)']) {
    const example = `You ${verb} *[shield](link_spell_4831)*.`;
    for (const code of [
      `\`${example}\``,
      `\`\`Example with a literal \` tick: ${example}\`\``,
      `\`\`\`markdown\n**Activate** Cast a Spell; **Effect** ${example}\n\`\`\``,
      `~~~markdown\n**Activate** Cast a Spell; **Effect** ${example}\n~~~~`,
    ]) {
      const text = `**Activate** Interact; **Effect** Example:\n${code}\n\n**Activate** Cast a Spell; **Effect** You ${verb} [heal](link_spell_4656).`;
      assert.deepEqual(
        detectSpellheartSpells(text, catalog).map(({ spell, rank }) => [spell.id, rank]),
        [[4656, 1]],
        code
      );
      assert.deepEqual(
        detectSpellheartSpells(`Example:\n${code}\nLegacy: [heal](link_spell_4656).`, catalog).map(
          ({ spell, rank }) => [spell.id, rank]
        ),
        [[4656, 1]],
        'Headerless first-link compatibility skips only literal code'
      );
    }
  }
});

test('spellheart conditions and prerequisites do not become additional casting activations', () => {
  const shield = { ...localSpell, id: 4831, name: 'Shield', rank: 0 };
  const heal = { ...localSpell, id: 4656, name: 'Heal', rank: 1 };
  for (const verb of ['cast', '[cast](link_action_19611)']) {
    for (const condition of ['If', 'When', 'After', 'Before', 'Unless']) {
      const text = `**Activate** Interact; **Effect** ${condition} you ${verb} [shield](link_spell_4831), the weapon glows. You ${verb} [heal](link_spell_4656).`;
      assert.deepEqual(
        detectSpellheartSpells(text, [shield, heal]).map(({ spell, rank }) => [spell.id, rank]),
        [[4656, 1]],
        `${condition}: the direct cast remains, the conditional example does not grant another spell`
      );
    }
    const text = `**Activate** Cast a Spell; **Requirements** You ${verb} [shield](link_spell_4831) earlier this turn; **Effect** You ${verb} [heal](link_spell_4656).`;
    assert.deepEqual(
      detectSpellheartSpells(text, [shield, heal]).map(({ spell, rank }) => [spell.id, rank]),
      [[4656, 1]],
      'A requirement is not an item casting effect'
    );
  }
});

test('spellheart casts come from effect prose, not later sentences in metadata or passive benefits', () => {
  const shield = { ...localSpell, id: 4831, name: 'Shield', rank: 0 };
  const heal = { ...localSpell, id: 4656, name: 'Heal', rank: 1 };
  for (const field of ['Requirements', 'Trigger', 'Armor', 'Weapon']) {
    const text = `**Activate** Cast a Spell; **${field}** You know an example spell. You [cast](link_action_19611) [shield](link_spell_4831) earlier this turn; **Effect** You [cast](link_action_19611) [heal](link_spell_4656).`;
    assert.deepEqual(
      detectSpellheartSpells(text, [shield, heal]).map(({ spell, rank }) => [spell.id, rank]),
      [[4656, 1]],
      `${field}: every sentence belongs to that field until the effect begins`
    );
  }
});

test('spellheart link labels and malformed nested links are not executable casting prose', () => {
  const shield = { ...localSpell, id: 4831, name: 'Shield', rank: 0 };
  const heal = { ...localSpell, id: 4656, name: 'Heal', rank: 1 };
  for (const example of [
    '[Example: **Effect** You cast [shield](link_spell_4831).](https://example.com/rules)',
    '[Example: **Effect** You [cast](link_action_19611) [shield](link_spell_4831).](link_item_11794)',
    '[Example](https://example.com/?text=Effect You cast [shield](link_spell_4831))',
    '[Example: You cast \\[shield\\](link_spell_4831).](https://example.com/rules)',
  ]) {
    const text = `**Activate** Interact; **Effect** ${example}\n\n**Activate** Cast a Spell; **Effect** You [cast](link_action_19611) *[heal](link_spell_4656)*.`;
    assert.deepEqual(
      detectSpellheartSpells(text, [shield, heal]).map(({ spell, rank }) => [spell.id, rank]),
      [[4656, 1]],
      example
    );
  }
});

test('linked casting verbs preserve Warding Statuette activations, ranks and repeated spell references', () => {
  const shield = { ...localSpell, id: 4831, name: 'Shield', rank: 0 };
  const armament = { ...localSpell, id: 4855, name: 'Spiritual Armament', rank: 2 };
  const catalog = [shield, armament];
  const text = [
    '**Armor** This resembles *[spiritual armament](link_spell_4855)*.',
    '**Activate** [Cast a Spell](link_action_19611); **Effect** You [cast](link_action_19611) *[shield](link_spell_4831)*.',
    '**Activate** [Cast a Spell](link_action_19611); **Frequency** once per day; **Effect** You [cast](link_action_19611) *[spiritual armament](link_spell_4855)*.',
    '**Activate** Cast a Spell; **Effect** You [Cast](link_action_19611) a 6th-rank *[spiritual armament](link_spell_4855)*.',
    '**Activate** Cast a Spell; **Effect** You cast *[shield](link_spell_4831)*.',
  ].join('\n\n');
  const original = structuredClone(catalog);
  assert.deepEqual(
    detectSpellheartSpells(text, catalog).map(({ spell, rank }) => [spell.id, spell.rank, rank]),
    [
      [4831, 0, 0],
      [4855, 2, 2],
      [4855, 6, 6],
    ]
  );
  assert.deepEqual(catalog, original);
});

test('linked noncasting actions and references outside a casting clause do not grant spells', () => {
  for (const clause of [
    'You [cast](link_action_19855)',
    'You [cast](link_item_19611)',
    'You [Stride](link_action_19611)',
    'You have [cast](link_action_19611)',
    'The item [casts](link_action_19611)',
  ]) {
    assert.deepEqual(
      detectSpellheartSpells(`**Activate** Interact; **Effect** ${clause} [petal storm](link_spell_8999).`, [
        petalStorm,
      ]),
      [],
      clause
    );
  }
});

test('headerless spellhearts preserve the first available linked spell and its explicit rank', () => {
  const directCast = 'You cast 6th-rank [petal storm](link_spell_8999). Then [elemental absorption](link_spell_8867).';
  assert.deepEqual(
    detectSpellheartSpells(directCast, [petalStorm, elementalAbsorption]).map(({ spell, rank }) => [
      spell.id,
      spell.rank,
      rank,
    ]),
    [[8999, 6, 6]]
  );
  const bareLinks = '[petal storm](link_spell_8999), [elemental absorption](link_spell_8867)';
  assert.deepEqual(
    detectSpellheartSpells(bareLinks, [petalStorm, elementalAbsorption]).map(({ spell, rank }) => [spell.id, rank]),
    [[8999, 4]]
  );
  assert.deepEqual(
    detectSpellheartSpells(bareLinks, [elementalAbsorption]).map(({ spell, rank }) => [spell.id, rank]),
    [[8867, 3]]
  );
  assert.deepEqual(detectSpellheartSpells(bareLinks, []), []);
  assert.equal(petalStorm.rank, 4);
});

test('existing book spellheart activation formats retain every linked cast spell', async () => {
  // The sanitized dump is an existing content fixture, not a production read.
  const dump = await readFile(join(root, '../data/data.sql'), 'utf8');
  const itemCopy = dump.match(/COPY public.item \((.*?)\) FROM stdin;\n([\s\S]*?)\n\\\./);
  assert.ok(itemCopy);
  const columns = itemCopy[1].split(', ').map((column) => column.replaceAll('"', ''));
  let spellheartCount = 0;
  for (const line of itemCopy[2].split('\n')) {
    const values = line.split('\t');
    const item = Object.fromEntries(columns.map((column, index) => [column, values[index]]));
    if (!/(?:\{|,)2570(?:,|\})/.test(item.traits ?? '')) continue;
    spellheartCount++;
    const description = item.description.replace(/\\n/g, '\n');
    const activationStart = description.search(/^\*\*Activate\*\*/im);
    assert.notEqual(activationStart, -1, `${item.name} activation header`);
    // Existing official fixture rows place only casting spell links after these headers.
    const expected = [
      ...new Set(
        [...description.slice(activationStart).matchAll(/\(link_spell_(\d+)\)/g)].map((match) => Number(match[1]))
      ),
    ].sort((a, b) => a - b);
    const catalog = expected.map((id) => ({ ...localSpell, id }));
    const actual = [...new Set(detectSpellheartSpells(description, catalog).map(({ spell }) => spell.id))].sort(
      (a, b) => a - b
    );
    assert.deepEqual(actual, expected, `${item.id} ${item.name}`);
    const linkedDescription = description.replace(/\byou\s+cast\b/gi, (clause) =>
      clause.replace(/cast$/i, '[cast](link_action_19611)')
    );
    assert.deepEqual(
      detectSpellheartSpells(linkedDescription, catalog).map(({ spell, rank }) => [spell.id, rank]),
      detectSpellheartSpells(description, catalog).map(({ spell, rank }) => [spell.id, rank]),
      `${item.id} ${item.name}: casting links cannot remove spells`
    );
  }
  assert.ok(spellheartCount > 0);
});

test('item reference eligibility matches existing panels and does not scan ordinary items or containers', () => {
  const wand = {
    ...brightbloom,
    id: 'wand',
    item: { ...brightbloom.item, traits: [1665], description: '[elemental absorption](link_spell_8867)' },
  };
  const ordinary = {
    ...brightbloom,
    id: 'ordinary',
    item: { ...brightbloom.item, traits: [], description: '[other spell](link_spell_7001)' },
  };
  const inheritedWand = {
    ...wand,
    id: 'inherited-wand',
    item: { ...wand.item, traits: [], meta_data: { base_item_content: { traits: [1665] } } },
  };
  assert.deepEqual(getInventorySpellIds([boreal, brightbloom, wand, inheritedWand, ordinary]), [8867, 8999]);
  assert.deepEqual(getInventorySpellIds([{ ...boreal, is_equipped: false }]), []);
  assert.deepEqual(
    getInventorySpellIds([
      { ...brightbloom, is_formula: true },
      { ...wand, is_formula: true },
    ]),
    [8867, 8999]
  );
  assert.deepEqual(getInventorySpellIds([{ ...ordinary, container_contents: [boreal, brightbloom] }]), []);
  assert.deepEqual(getInventorySpellIds([brightbloom]), [8999]);
  assert.equal(brightbloom.is_invested, false);
  assert.equal(brightbloom.is_equipped, false);
});

test('dependency reads are unique exact IDs and source-enabled rows win over returned duplicates', () => {
  const current = { ...petalStorm, name: 'Current catalog Petal Storm' };
  const catalog = [localSpell, current];
  assert.deepEqual(getMissingSpellIds(catalog, [8999, 8867, 8867, -1, 0]), [8867]);
  assert.deepEqual(
    mergeSpellDependencies(catalog, [petalStorm, elementalAbsorption, elementalAbsorption, { id: 90 }], [8867]),
    [localSpell, current, elementalAbsorption]
  );
  assert.equal(mergeSpellDependencies(catalog, undefined, [8867]), catalog);
  assert.equal(mergeSpellDependencies(catalog, [elementalAbsorption], []), catalog);
  assert.deepEqual(catalog, [localSpell, current]);
});

test('search and action filters combine for delayed item spells and clear without changing the catalog', () => {
  const catalog = [localSpell, elementalAbsorption, petalStorm];
  const traits = () => ['wood'];
  assert.deepEqual(filterSpellCatalog(catalog, ' PETAL ', 'ALL', traits), [petalStorm]);
  assert.deepEqual(filterSpellCatalog(catalog, '', 'TWO-ACTIONS', traits), [elementalAbsorption, petalStorm]);
  assert.deepEqual(filterSpellCatalog(catalog, 'petal', 'TWO-ACTIONS', traits), [petalStorm]);
  assert.deepEqual(filterSpellCatalog(catalog, 'petal', 'ONE-ACTION', traits), []);
  assert.deepEqual(filterSpellCatalog(catalog, 'wood', 'TWO-ACTIONS', traits), [elementalAbsorption, petalStorm]);
  assert.equal(filterSpellCatalog(catalog, '', 'ALL', traits), catalog);
});

test('explicit ranks stay local to their spell and preserve normal, legacy, wand and staff parsing', () => {
  const text =
    '**Effect** Cast 6th-rank *[petal storm](link_spell_8999)*.\n\n**Effect** Cast [elemental absorption](link_spell_8867).';
  assert.deepEqual(
    detectSpells(text, [petalStorm, elementalAbsorption], true).map(({ spell, rank }) => [spell.id, spell.rank, rank]),
    [
      [8999, 6, 6],
      [8867, 3, 3],
    ]
  );
  assert.equal(detectSpells('Cast 6th-level [petal storm](link_spell_8999).', [petalStorm], true)[0].rank, 6);
  assert.equal(detectSpells('Cast 10th-rank [petal storm](link_spell_8999).', [petalStorm], true)[0].rank, 10);
  assert.equal(detectSpells('Lasts 6 rounds. Cast [petal storm](link_spell_8999).', [petalStorm], true)[0].rank, 4);
  assert.equal(detectSpells('Cast 11th-rank [petal storm](link_spell_8999).', [petalStorm], true)[0].rank, 4);
  assert.equal(detectSpells('A regular wand casts [petal storm](link_spell_8999).', [petalStorm], true)[0].rank, 4);
  assert.deepEqual(
    detectSpells(
      '* **3rd** [elemental absorption](link_spell_8867)\n* **6th** [elemental absorption](link_spell_8867)',
      [elementalAbsorption]
    ).map(({ spell, rank }) => [spell.id, spell.rank, rank]),
    [
      [8867, 3, 3],
      [8867, 6, 6],
    ]
  );
  assert.equal(petalStorm.rank, 4);
  assert.equal(elementalAbsorption.rank, 3);
});

const baseScope = {
  actorId: 'actor-a',
  entityId: 1,
  storeId: 'CHARACTER',
  infoSources: 'public',
  pageSources: '16',
  ids: [8867],
};
const settled = () => new Promise((resolve) => setImmediate(resolve));

test('query ownership, entity, source and inventory changes cannot publish late dependency rows', async (t) => {
  for (const [name, change] of [
    ['account', { actorId: 'actor-b' }],
    ['entity', { entityId: 2 }],
    ['store', { storeId: 'COMPANION' }],
    ['information sources', { infoSources: 'public-and-owned' }],
    ['enabled sources', { pageSources: '16,842' }],
    ['inventory references', { ids: [8999] }],
  ])
    await t.test(name, async () => {
      const client = new QueryClient({
        defaultOptions: { queries: { retry: false, gcTime: Infinity, staleTime: 60000 } },
      });
      const pending = [];
      globalThis.__itemSpellFetch = (type, data) => new Promise((resolve) => pending.push({ type, data, resolve }));
      const observer = new QueryObserver(client, getExplicitSpellQueryOptions(baseScope));
      const unsubscribe = observer.subscribe(() => {});
      assert.deepEqual(
        pending.map(({ type, data }) => [type, data]),
        [['spell', { id: [8867] }]]
      );
      const currentScope = { ...baseScope, ...change };
      observer.setOptions(getExplicitSpellQueryOptions(currentScope));
      assert.equal(pending.length, 2);
      pending[0].resolve([elementalAbsorption]);
      await settled();
      assert.equal(observer.getCurrentResult().data, undefined);
      const current =
        currentScope.ids[0] === 8999 ? petalStorm : { ...elementalAbsorption, name: 'Current scoped spell' };
      pending[1].resolve([current]);
      await settled();
      assert.deepEqual(observer.getCurrentResult().data, [current]);
      unsubscribe();
      observer.destroy();
      client.clear();
    });
});

test('removing the last item clears its supplement immediately even when its read completes later', async () => {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity } } });
  let finish;
  globalThis.__itemSpellFetch = () =>
    new Promise((resolve) => {
      finish = resolve;
    });
  const observer = new QueryObserver(client, getExplicitSpellQueryOptions(baseScope));
  const unsubscribe = observer.subscribe(() => {});
  observer.setOptions(getExplicitSpellQueryOptions({ ...baseScope, ids: [] }));
  assert.equal(observer.getCurrentResult().data, undefined);
  assert.equal(getExplicitSpellQueryOptions({ ...baseScope, ids: [] }).enabled, false);
  assert.equal(mergeSpellDependencies([localSpell], [elementalAbsorption], [])[0], localSpell);
  finish([elementalAbsorption]);
  await settled();
  assert.equal(observer.getCurrentResult().data, undefined);
  unsubscribe();
  observer.destroy();
  client.clear();
});

test('a failed optional dependency read leaves source-enabled spells available without adding rows', async () => {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity } } });
  globalThis.__itemSpellFetch = async () => {
    throw new Error('Offline');
  };
  const observer = new QueryObserver(client, getExplicitSpellQueryOptions(baseScope));
  const unsubscribe = observer.subscribe(() => {});
  await settled();
  assert.equal(observer.getCurrentResult().isError, true);
  assert.equal(mergeSpellDependencies([localSpell], observer.getCurrentResult().data, [8867])[0], localSpell);
  unsubscribe();
  observer.destroy();
  client.clear();
});
