/* Copyright (C) 2021, Wanderer's Guide, all rights reserved.
    By Aaron Cassar.
*/

let g_materialsMap = new Map();

g_materialsMap.set('ABYSIUM', {Name: 'Abysium', Description: 'A blue-green metal with an eerie green luminescence, abysium radiates power that’s inimical to life. Careless exposure to the material can lead to long-term damage to the immune system; as such, mining abysium is hazardous, as large quantities of the metal in an area cause all nearby creatures to become sick. A creature carrying an abysium object is sickened 1 for a standard-grade object of light Bulk, sickened 2 for a standard-grade object of 1 Bulk or more or a high-grade object of light Bulk, or sickened 3 for a high-grade object of 1 Bulk or more. This and all other sickening effects of abysium are poison effects. Crafters can use 1 abysium chunk to create up to 6 doses of poisonous abysium powder. Unscrupulous smiths have harnessed abysium’s toxic properties to create noxious weapons and deadly substances. All objects crafted from abysium shed dim light in a 10-foot radius. See more on Lost Omens Grand Bazaar pg. 96.'});
g_materialsMap.set('ADAMANTINE', {Name: 'Adamantine', Description: 'Mined from rocks that fell from the heavens, adamantine is one of the hardest metals known. It has a shiny, black appearance, and it is prized for its amazing resiliency and ability to hold an incredibly sharp edge. See more on page 578.'});
g_materialsMap.set('COLD IRON', {Name: 'Cold Iron', Description: 'Weapons made from cold iron are deadly to demons and fey alike. Cold iron looks like normal iron but is mined from particularly pure sources and shaped with little or no heat. This process is extremely difficult, especially for high-grade cold iron items. See more on page 578.'});
g_materialsMap.set('DARKWOOD', {Name: 'Darkwood', Description: 'Darkwood is a very lightweight wood found primarily in old-growth forests; it is dark as ebony but has a slight purple tint. A darkwood item’s Bulk is reduced by 1 (or to light Bulk if its normal Bulk is 1, with no effect on an item that normally has light Bulk). See more on page 578.'});
g_materialsMap.set('DJEZET', {Name: 'Djezet', Description: 'This rust red metal is liquid at room temperature, making it challenging for all but the most skilled metallurgists to craft with and earning it the name “quickiron” in some places. Djezet is also extremely reactive to magic, even in its solid, workable alloyed form. It glows when targeted by magic, and objects crafted with djezet alloys glow with scarlet striations, which lead some smiths to nickname it “tiger iron.” When targeted by spells, objects crafted from djezet alloys exhibit these glowing red markings that last for 1 round or the duration of the spell, whichever is longer. A djezet mass contains enough djezet to refine into up to two djezet doses (pg. 98). See more on Lost Omens Grand Bazaar pg. 97.'});
g_materialsMap.set('DRAGONHIDE', {Name: 'Dragonhide', Description: 'Dragonhide varies in color from blue to glittering gold, depending on the dragon it came from. Due to the scales’ resiliency, it can also be used to Craft armor usually made out of metal plates (such as a breastplate, half plate, and full plate), allowing such armor to be made without metal. Dragonhide objects are immune to one damage type, depending on the type of dragon. See more on page 579.'});
g_materialsMap.set('GRISANTIAN PELT', {Name: 'Grisantian Pelt', Description: 'Highly desired for the prestige, the pelt of the grogrisant also has invaluable properties. Standard-grade items can be made from the pelt of a grisantian lion, but high-grade items require the pelt of the grogrisant itself. This supernaturally tough animal skin is gold and shines in sunlight. It can be used to make any item usually made of cloth, leather, or hide. This material is immune to fire, and its Hardness is doubled against piercing or slashing damage. Up to 4 Bulk of grisantian pelt can be harvested from a single creature (this is usually more than enough for 4 suits of standard grade armor or 2 suit of high-grade armor).'});
g_materialsMap.set('INUBRIX', {Name: 'Inubrix', Description: 'This pale, malleable metal’s unusual molecular structure allows it to partially pass through iron and steel without touching them. While this property is useful for making weapons that bypass metal armor, inubrix is barely sturdier than lead. Even in an alloyed state, this skymetal is so fragile that it’s difficult to use in crafting reliable shields and less than ideal for crafting armor. See more on Lost Omens Grand Bazaar pg. 98.'});
g_materialsMap.set('MITHRAL', {Name: 'Mithral', Description: 'Mithral is renowned for its lightness, durability, and effectiveness against a range of creatures including devils and lycanthropes. It has the same sheen as silver but a slightly lighter hue. Mithral weapons and armor are treated as if they were silver for the purpose of damaging creatures with weakness to silver. A metal item made of mithral is lighter than one made of iron or steel: the item’s Bulk is reduced by 1 (reduced to light Bulk if its normal Bulk is 1, with no effect on an item that normally has light Bulk). See more on page 579.'});
g_materialsMap.set('NOQUAL', {Name: 'Noqual', Description: 'Light and strong, noqual also demonstrates a powerful resistance to magic. A side effect of this resistance is that making magical weapons out of noqual requires complex and expensive alchemical treatments. Kevoth-Kul, the Black Sovereign of Numeria, has developed an alloy of noqual and cold iron known as sovereign steel to help mitigate this property. The metal’s crystalline appearance might suggest that it’s fragile, but the pale-green material can be worked similarly to iron. Objects made of noqual have a +4 circumstance bonus on saves against magic that the item attempts and grant their bonus to saves the owner makes specifically to protect the item from magic (such as against the rusting grasp spell). See more on Lost Omens Grand Bazaar pg. 99.'});
g_materialsMap.set('ORICHALCUM', {Name: 'Orichalcum', Description: 'The most rare and valuable skymetal, orichalcum is coveted for its incredible time-related magical properties. This dull, coppery metal isn’t as physically sturdy as adamantine, but orichalcum’s time-bending properties protect it, granting it greater Hardness and Hit Points. If an orichalcum item takes damage but isn’t destroyed, it repairs itself completely 24 hours later. See more on page 579.'});
g_materialsMap.set('PEACHWOOD', {Name: 'Peachwood', Description: 'Peachwood, often cultivated by Pharasma priests, can ward against undead—even incorporeal ones. However, the wood loses its magical properties when it comes in contact with metal, requiring advanced carpentry to make full use of it.'});
g_materialsMap.set('SICCATITE', {Name: 'Siccatite', Description: 'In its raw state, this silvery ore is either scalding hot or freezing cold. Metallurgists disagree over whether siccatite is two related substances or one substance that determines its temperature output via some unknown process. Whatever the reason, the extreme temperature of the material means it must be handled carefully. Hot siccatite can easily ignite flammables such as paper and dry brush, and cold siccatite left in moist areas quickly surrounds itself with a thick layer of ice. A creature that comes into physical contact with a significant amount of siccatite takes 1 energy damage for each round of continued contact (either fire or cold damage, for hot and cold siccatite respectively). See more on Lost Omens Grand Bazaar pg. 100.'});
g_materialsMap.set('SILVER', {Name: 'Silver', Description: 'Silver weapons are a bane to creatures ranging from devils to werewolves. Silver items are less durable than steel items, and low-grade silver items are usually merely silver-plated. See more on page 579.'});
g_materialsMap.set('SISTERSTONE', {Name: 'Sisterstone', Description: 'Sisterstone is a term used for two closely related ores infused by the spiritual runoff in the Field of Maidens, dusk sisterstone and scarlet sisterstone. They have the same physical properties except for color—dusk sisterstone is a pale orange while scarlet sisterstone is orange-red. When near an object made of the other type of sisterstone, they both begin exuding spiritual energy that repels undead. \n When an object made of dusk sisterstone is within 15 feet of an object made of scarlet sisterstone of the same grade, they create a reciprocal field. Any undead creature adjacent to one of the objects when the field is formed, or who moves adjacent to one while the field is active, becomes enfeebled 1 unless it succeeds at a DC 15 Fortitude save. This lasts until the undead creature is no longer adjacent to either of the items or until the field\'s removed (typically by the objects ceasing to be within 15 feet of one another). The DC increases to 22 if both items are standard grade or better, and to 33 if they\'re both high grade. Unworked chunks and ingots don\'t create a reciprocal field. A single object can\'t be made of both types of sisterstone.'});
g_materialsMap.set('SOVEREIGN STEEL', {Name: 'Sovereign Steel', Description: 'This unique alloy of cold iron and the skymetal noqual can provide protection from magical assault. The process of cold-forging the two materials together is quite complicated and precise. All sovereign steel items have a +4 circumstance bonus on saves against magic that the item makes, and grant their bonus to saves the owner makes specifically to protect the item from magic.'});
g_materialsMap.set('WARPGLASS', {Name: 'Warpglass', Description: 'This bizarre substance is fashioned from the raw, chaotic quintessence of the Maelstrom. It can be fashioned into weapons and items, but is too unstable to make into useful armor or shields. Raw warpglass is an opalescent glassy material with surprising strength. When worked, it changes its appearance - though not its properties - to appear as random striations of other metals and types of stone.'});